<?php

namespace filib\sitemapgenerator;

use Craft;
use craft\base\Model;
use craft\base\Plugin;
use craft\db\Query;
use filib\sitemapgenerator\models\Settings;

/**
 * Sitemap Generator plugin
 *
 * @method static SitemapGenerator getInstance()
 * @method Settings getSettings()
 */
class SitemapGenerator extends Plugin
{
    public static SitemapGenerator $plugin;
    public bool $hasCpSettings = true;
    public array $loadedSettings = [];


    public function init(): void
    {
        parent::init();
        self::$plugin = $this;
        if ($this->isInstalled) {
            $this->loadSettingsFromDatabase();
        }
    }

    public function loadSettingsFromDatabase(): void
    {
        $rows = (new Query())
            ->select(['id', 'handle', 'name', 'weight', 'enabled', 'hasUrls'])
            ->from('{{%sitemapgenerator}}')
            ->all();

        $entryTypes = [];

        foreach ($rows as $row) {
            $entryTypes[$row['id']] = [
                'id' => (string)$row['id'],
                'handle' => (string)$row['handle'],
                'name' => (string)$row['name'],
                'weight' => (int)$row['weight'],
                'enabled' => (bool)$row['enabled'],
                'hasUrls' => (bool)$row['hasUrls'],
            ];
        }

        $this->loadedSettings = [
            'entrySettings' => $entryTypes
        ];

        $this->setSettings($this->loadedSettings);
    }

    public function afterInstall(): void
    {
        parent::afterInstall(); // TODO: Change the autogenerated stub

        $this->loadSettingsFromDatabase();
    }

    public function getLoadedSettings(): array
    {
        return $this->loadedSettings;
    }

    public function getSettingsResponse(): ?string
    {
        $this->loadSettingsFromDatabase();
        return Craft::$app->controller->renderTemplate('sitemapgenerator/settings.twig', [
            'entryTypes' => $this->getSettings()->entrySettings
        ]);
    }

    protected function createSettingsModel(): ?Model
    {
        return new Settings();
    }
}
